name: Boardworld
favicon: null
layout_spectrum: 0.6235045078210533
typography_spectrum: 0.024312217719852924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3402555361390114
  lightness: 0.2210510151926428
  saturation: 0.13719251984730363
  rhythmicContrast: 0.9668917676899582
purpose: []
